import type { Metadata } from "next";
import "../globals.css"; // Adjust the path based on the actual location
import { ThemeProvider } from "@/components/theme-provider";
import AccessibilityWidget from "@/components/AccessibilityWidget";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';

export const metadata: Metadata = {
  title: "Caritas Microfinance Bank",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <>
      <html lang={locale} suppressHydrationWarning>
        <head />
        <body className="bg-gray-100">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider>
            {children}
            </NextIntlClientProvider>
          </ThemeProvider>
          <AccessibilityWidget />
        </body>
      </html>
    </>
  );
}
